# Permalinks
permalink:           pretty

# Setup
title:               iOS tips and hacks
tagline:             EugeneiOS 
url:                 http://getpoole.com
paginate:            1
baseurl:             ""
markdown:            kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed
  highlighter:       rouge

# About/contact
author:
  name:              EugeneiOS
  url:               eugenegoloboyar.github.io

# Custom vars
version:             2.0.0
github:
  repo:              eugenegoloboyar.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

